### ISSUE TITLE
picture is not returning in image element

### ISSUE THREAD

**Issue by flik** [davgothic/AjaxFileUpload#9] opened 2017-01-14 12:47 UTC
$("#uploads").append(
						$("<img />").attr("src", filename).attr("width", 200)
					);

this code is not working

**Comment by SirChristian123** [comment] 2017-05-28 19:41
What browser are you using? I tested it and it worked for me. As far as I know and I may be wrong, when you see the page source code you won't see the img element because the request you are doing is asynchronously.

![image](https://cloud.githubusercontent.com/assets/16406994/26531675/9be93daa-43bb-11e7-9142-66e0c88bf8e8.png)
![image](https://cloud.githubusercontent.com/assets/16406994/26531678/abad7f44-43bb-11e7-83ec-913289cd7942.png)

**Comment by davgothic** [comment] 2017-09-15 09:15
I cannot reproduce the issue although it does look to me like your empty selector could be the cause? Closing for now.

**Closed by davgothic** 2017-09-15 09:15 UTC
