### ISSUE TITLE
json error is coming 

### ISSUE THREAD

**Issue by flik** [davgothic/AjaxFileUpload#10] opened 2017-01-14 12:49 UTC
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by nlounds** [comment] 2017-06-22 14:46
I am getting the same or a very similar error.  It only occurs on the server, not when we're developing on our local machines.

Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)

**Comment by davgothic** [comment] 2017-09-15 09:17
I cannot reproduce this issue. It is likely that @nlounds is correct and you are accidentally sending malformed JSON to the browser.

Closing for now.

**Closed by davgothic** 2017-09-15 09:17 UTC
